spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pipelineforge?createDatabaseIfNotExist=true
    username: root
    password: cocffyt.

# Disable SQS for local testing
aws:
  sqs:
    queue-url: ""